# Generated by Django 6.0.1 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverycharge_order_gift_message_order_gift_wrap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=10, null=True),
        ),
    ]
