# Generated by Django 6.0.1 on 2026-01-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('CHANGED_MIND', 'Changed my mind'), ('WRONG_ITEM', 'Ordered wrong item'), ('DELAYED', 'Delivery taking too long'), ('FOUND_CHEAPER', 'Found cheaper elsewhere'), ('STOCK_ISSUE', 'Stock unavailable'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Refund Initiated'), ('PROCESSING', 'Refund Processing'), ('COMPLETED', 'Refund Completed'), ('FAILED', 'Refund Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='orders.order')),
            ],
        ),
    ]
