# Generated by Django 6.0.1 on 2026-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cancel_reason_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_note',
            field=models.TextField(blank=True, help_text='Custom reason if Other selected', null=True),
        ),
    ]
