# Generated by Django 6.0.1 on 2026-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show on homepage'),
        ),
    ]
