# Generated by Django 6.0.1 on 2026-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Check this to show this category on the homepage', verbose_name='Is New (Show on Home)'),
        ),
    ]
